USE sanastours_db;

#INSERT DATA INTO TourPackage
INSERT INTO TourPackage (package_id, package_name, description, price, duration_days) VALUES
('P01', 'Short Break 3 Days', 'A short cultural tour covering Sigiriya, Dambulla, Kandy and airport transfer.',
450.00, 3),
('P02', 'Cultural Escape 4D', 'A four-day Sri Lanka cultural tour covering Sigiriya, Kandy and Colombo.',
650.00, 4),
('P03', 'Wildlife Coast 4D','A wildlife and beach holiday covering Colombo, Udawalawe and Galle.',
720.00, 4),
('P04', 'Hill Country 4D','A scenic holiday covering Kandy, Nuwara Eliya and Colombo.',
680.00, 4),
('P05','Classic Sri Lanka 9D','A complete Sri Lankan holiday including Negombo, Dambulla, Kandy, Nuwara Eliya, Yala and Galle.',
1450.00, 9),
('P06', 'Land and Sea 14D','Culture, hill country, wildlife and a southern coast cruise.',
 2650.00, 14),
('P07', 'Island Romance 9D','A romantic journey through Kandy, Ella, Yala and Galle.',
 1890.00, 9),
('P08', 'Wellness Journey 14D','Cultural visits, meditation in Kandy and an Ayurveda resort stay.',
 2350.00, 14),
('P09', 'Rustic Retreats 14D','Forest walks, outdoor adventures, wildlife and eco retreats.',
 2490.00, 14),
('P10', 'Anasa Wellness 10D','A wellness resort programme in Bandarawela with time in Galle.',
 2100.00, 10),
('P11', 'Leopard Trails 15D','Wildlife safaris across Wilpattu, Kumana, Bundala and Yala.',
 2890.00, 15),
('P12', 'Family Escape 15D','A relaxed family tour through Sigiriya, Kandy, Ella, Yala and Tangalle.',
 2450.00, 15),
('P13', 'Amaya Retreats 12D','A luxury-style tour through Koggala, Nanu Oya, Kandy and Pasikudah.',
 2750.00, 12),
('P14', 'Off Road Adventure 15D','Sand dunes, four-wheel-drive routes, hill-country activities and safaris.',
 2590.00, 15),
('P15', 'Kandy Bentota 6D','A short holiday visiting Colombo, Kandy, Nuwara Eliya and Bentota.',
 990.00, 6),
('P16', 'Sri Lankan Homes 16D','A journey through heritage sites, hill country, eastern beaches, wildlife and coastal towns.',
2950.00, 16),
('P17', 'Cinnamon Local Vibe 14D','A tour of cultural sites, eastern beaches, tea country, wildlife and Bentota.',
2750.00, 14),
('P18', 'Feathered Trails 15D','A birding-focused journey through wetlands, forests, hill country and national parks.',
2850.00, 15),
('P19', 'Echoes of Wild 15D','A wildlife journey through Wilpattu, Wasgamuwa, Gal Oya, Kumana and Mirissa.',
2990.00, 15),
('P20', 'Lanka Maldives 15D','A family adventure combining Sri Lankan hill country and wildlife with a Maldives beach stay.',
3250.00, 15);

#INSERT DATA INTO Destination
INSERT INTO Destination(destination_id, destination_name, description) VALUES
('D0001','Sigiriya',
'Historic destination famous for Sigiriya Rock Fortress and nearby cultural attractions.'),
('D0002','Dambulla',
'Cultural city known for the Dambulla Cave Temple.'),
('D0003','Kandy','Hill-country city known for the Temple of the Tooth, Kandy Lake and cultural dance shows.'),
('D0004','Colombo',
'Commercial capital of Sri Lanka with city attractions, shopping and historical areas.'),
('D0005','Udawalawe',
'Wildlife destination known for Udawalawe National Park and Elephant Transit Home.'),
('D0006','Galle',
'Southern coastal city famous for Galle Dutch Fort, beaches and colonial architecture.'),
('D0007','Nuwara Eliya',
'Cool hill-country destination known as Little England, tea estates and waterfalls.'),
('D0008','Negombo',
'Coastal town near the airport, known for fishing villages and beach hotels.'),
('D0009','Yala','Wildlife destination famous for Yala National Park and jeep safaris.'),
('D0010','Pinnawala',
'Popular destination known for elephant-related attractions.'),
('D0011', 'Ella',
 'Hill-country stop featured in train journeys, walks and adventure activities.'),
('D0012', 'Unawatuna',
 'Southern beach stop featured in the Land and Sea tour.'),
('D0013', 'Mirissa',
 'Southern harbour and coastal stop featured in cruise itineraries.'),
('D0014', 'Kotugoda',
 'Arrival and rest stop featured in family and romance itineraries.'),
('D0015', 'Aluthgama',
 'Resort stop featured in the Ayurveda and meditation itinerary.'),
('D0016', 'Kalutara',
 'Resort base featured at the beginning of the Rustic Retreats tour.'),
('D0017', 'Sinharaja',
 'Rainforest excursion featured in nature and wildlife itineraries.'),
('D0018', 'Belihuloya',
 'Outdoor adventure and campsite stop.'),
('D0019', 'Gal Oya',
 'Wildlife destination featured in safari and boat excursions.'),
('D0020', 'Maduru Oya',
 'National park and campsite featured in the Rustic Retreats tour.'),
('D0021', 'Makandura',
 'Final resort stop in the Rustic Retreats itinerary.'),
('D0022', 'Bandarawela',
 'Hill-country base for the Anasa wellness programme.'),
('D0023', 'Wilpattu',
 'National park destination featured in the Leopard Trails itinerary.'),
('D0024', 'Habarana',
 'Village and safari base featured in several itineraries.'),
('D0025', 'Panama',
 'Overnight base for visits to Kumana in the Leopard Trails itinerary.'),
('D0026', 'Kumana',
 'National park featured in wildlife safari itineraries.'),
('D0027', 'Bundala',
 'National park visit featured in the Leopard Trails itinerary.'),
('D0028', 'Tangalle',
 'Southern beach stay featured in the family tour.'),
('D0029', 'Koggala',
 'Coastal resort stay featured in the Amaya Retreats tour.'),
('D0030', 'Nanu Oya',
 'Hill-country stop featured in scenic rail and resort itineraries.'),
('D0031', 'Pasikudah',
 'East-coast beach stay featured in the Amaya Retreats tour.'),
('D0032', 'Polonnaruwa',
 'Ancient-city visit featured in several cultural itineraries.'),
('D0033', 'Kalpitiya',
 'Coastal and sand-dune destination in the off-road tour.'),
('D0034', 'Anuradhapura',
 'Ancient-city visit featured in cultural and adventure routes.'),
('D0035', 'Bentota',
 'Beach destination featured in the six-day Kandy and Nuwara Eliya tour.'),
('D0036', 'Weligama',
 'Bay visited during the southern coast cruise.'),
('D0037', 'Kudawella',
 'Coastal stop on the Land and Sea cruise.'),
('D0038', 'Kalametiya',
 'Lagoon and coastal stop on the Land and Sea cruise.'),
('D0039', 'Hiriketiya',
 'Beach stop on the Land and Sea cruise.'),
 ('D0040', 'Tallala',
 'Beach stop on the Land and Sea cruise.'),
('D0041', 'Wellawaya',
'Rural and outdoor activity stop in the 16-day Sri Lankan Homes itinerary.'),
('D0042', 'Pottuvil',
'East-coast beach stop in the 16-day Sri Lankan Homes itinerary.'),
('D0043', 'Trincomalee',
'East-coast beach destination in the Cinnamon Local Vibe itinerary.'),
('D0044', 'Mannar',
'Coastal and wetland birding stop in the Feathered Trails itinerary.'),
('D0045', 'Kitulgala',
'Forest and rafting stop featured in the birding and family adventure itineraries.'),
('D0046', 'Wasgamuwa',
'National park stop featured in the Echoes of the Wild itinerary.'),
('D0047', 'Maldives',
'Island beach stay forming the final part of the Sri Lanka and Maldives itinerary.');

#3. INSERT DATA INTO PackageDestination
INSERT INTO PackageDestination (package_id, destination_id, day_order) VALUES
-- P01: Short Break 3 Days
('P01', 'D0001', 1),('P01', 'D0002', 1),('P01', 'D0003', 2),

-- P02: Cultural Escape 4 Days
('P02', 'D0001', 1),('P02', 'D0002', 1),('P02', 'D0003', 2),('P02', 'D0004', 3),

-- P03: Wildlife Coast 4 Days
('P03', 'D0004', 1),('P03', 'D0005', 2),('P03', 'D0006', 3),

-- P04: Hill Country 4 Days
('P04', 'D0003', 1),('P04', 'D0007', 2),('P04', 'D0004', 3),

-- P05: Classic Sri Lanka 9 Days
('P05', 'D0008', 1),('P05', 'D0002', 2),('P05', 'D0001', 3),('P05', 'D0003', 4),
('P05', 'D0007', 5),('P05', 'D0009', 6),('P05', 'D0006', 7),

-- P06: Land and Sea
('P06', 'D0008', 1), ('P06', 'D0003', 2), ('P06', 'D0007', 4),('P06', 'D0011', 4),
('P06', 'D0005', 6),('P06', 'D0012', 7), ('P06', 'D0013', 8), ('P06', 'D0036', 8),   
('P06', 'D0037', 9), ('P06', 'D0038', 10), ('P06', 'D0039', 11), ('P06', 'D0040', 11),  
('P06', 'D0006', 13), 

-- P07: Island Romance
('P07', 'D0014', 1), ('P07', 'D0003', 2), ('P07', 'D0011', 3), ('P07', 'D0009', 5),   
('P07', 'D0006', 7),   

-- P08: Wellness Journey
('P08', 'D0008', 1), ('P08', 'D0002', 2), ('P08', 'D0001', 4), ('P08', 'D0003', 4),   
('P08', 'D0015', 7),   

-- P09: Rustic Retreats
('P09', 'D0016', 1), ('P09', 'D0017', 3), ('P09', 'D0018', 4), ('P09', 'D0019', 6),   
('P09', 'D0020', 8),('P09', 'D0002', 10), ('P09', 'D0001', 11), ('P09', 'D0021', 13),  

-- P10: Anasa Wellness
('P10', 'D0006', 1), ('P10', 'D0022', 2), ('P10', 'D0011', 8),   

-- P11: Leopard Trails
('P11', 'D0023', 1), ('P11', 'D0024', 4), ('P11', 'D0001', 5), ('P11', 'D0003', 5),   
('P11', 'D0007', 6), ('P11', 'D0025', 8), ('P11', 'D0026', 9), ('P11', 'D0009', 11),  
('P11', 'D0027', 11), ('P11', 'D0006', 14),  

-- P12: Family Escape
('P12', 'D0014', 1), ('P12', 'D0001', 3), ('P12', 'D0003', 5), ('P12', 'D0011', 7),
('P12', 'D0009', 9), ('P12', 'D0028', 11),

-- P13: Amaya Retreats
('P13', 'D0029', 1), ('P13', 'D0030', 3), ('P13', 'D0003', 5), ('P13', 'D0031', 7),
('P13', 'D0032', 9), ('P13', 'D0002', 9), ('P13', 'D0001', 10), ('P13', 'D0004', 11),

-- P14: Off Road Adventure
('P14', 'D0033', 1), ('P14', 'D0034', 3), ('P14', 'D0024', 3), ('P14', 'D0001', 5),
('P14', 'D0019', 5), ('P14', 'D0011', 7), ('P14', 'D0018', 9), ('P14', 'D0005', 12),
('P14', 'D0004', 14),

-- P15: Kandy Bentota
('P15', 'D0004', 1), ('P15', 'D0010', 2), ('P15', 'D0003', 2), ('P15', 'D0007', 3),
('P15', 'D0035', 4),

 -- P16: Sri Lankan Homes, 16 days
('P16', 'D0008', 1), ('P16', 'D0002', 2), ('P16', 'D0001', 2),('P16', 'D0003', 4),
('P16', 'D0007', 6),('P16', 'D0041', 8), ('P16', 'D0042', 10), ('P16', 'D0009', 12),
('P16', 'D0006', 13), ('P16', 'D0012', 14), ('P16', 'D0004', 15),

    -- P17: Cinnamon Local Vibe, 14 days
('P17', 'D0004', 1), ('P17', 'D0002', 2), ('P17', 'D0024', 2), ('P17', 'D0034', 3),
('P17', 'D0001', 4), ('P17', 'D0043', 4), ('P17', 'D0003', 6), ('P17', 'D0007', 8),
('P17', 'D0011', 9), ('P17', 'D0009', 9), ('P17', 'D0006', 11),('P17', 'D0035', 11), 

    -- P18: Feathered Trails, 15 days
('P18', 'D0023', 1), ('P18', 'D0044', 3), ('P18', 'D0001', 5), ('P18', 'D0002', 7),
('P18', 'D0045', 7), ('P18', 'D0007', 8), ('P18', 'D0009', 10), ('P18', 'D0027', 10),
('P18', 'D0005', 12), ('P18', 'D0017', 13), 

    -- P19: Echoes of Wild, 15 days
('P19', 'D0023', 1), ('P19', 'D0001', 3), ('P19', 'D0002', 4), ('P19', 'D0032', 5),
('P19', 'D0046', 5), ('P19', 'D0007', 7), ('P19', 'D0019', 9), ('P19', 'D0026', 11), 
('P19', 'D0013', 13), 

    -- P20: Lanka Maldives, 15 days
('P20', 'D0004', 1), ('P20', 'D0045', 3), ('P20', 'D0007', 5), ('P20', 'D0011', 7), 
('P20', 'D0009', 9), ('P20', 'D0047', 11);

#4. INSERT DATA INTO Itinerary
INSERT INTO Itinerary (package_id, day_number, title, description) VALUES
-- P01: Short Break 3 Days
('P01', 1,'Arrival and Sigiriya Exploration',
'Airport pickup and transfer to Sigiriya. Visit Dambulla Cave Temple and check in to the hotel in Sigiriya.'),
('P01', 2, 'Sigiriya and Kandy',
'Climb Sigiriya Lion Rock in the morning. Transfer to Kandy and visit the Temple of the Tooth Relic in the evening.'),
('P01', 3,'Kandy to Airport',
'Enjoy a short Kandy city experience before transferring to the airport for departure.'),

-- P02: Cultural Escape 4 Days
('P02', 1, 'Airport to Sigiriya',
'Airport pickup and transfer to Sigiriya. Visit Dambulla Cave Temple on the way and stay overnight in Sigiriya.'),
('P02', 2, 'Sigiriya to Kandy',
'Explore Sigiriya Lion Rock in the morning. Transfer to Kandy, visit Matale Alu Viharaya Temple and watch a cultural dance show.'),
('P02', 3, 'Kandy to Colombo',
'Visit the Temple of the Tooth, explore Kandy city and transfer to Colombo via Peradeniya Royal Botanical Gardens.'),
('P02', 4, 'Colombo City Tour',
'Explore Colombo city attractions, shopping areas and historical places before airport transfer.'),

-- P03: Wildlife Coast 4 Days
('P03', 1, 'Arrival in Colombo',
'Airport pickup, transfer to Colombo and a Colombo city tour. Overnight stay in Colombo.'),
('P03', 2, 'Colombo to Udawalawe',
'Transfer to Udawalawe. Visit the Elephant Transit Home and enjoy an afternoon jeep safari in Udawalawe National Park.'),
('P03', 3,'Udawalawe to Galle',
'Transfer to Galle. Stop for stilt fisherman photographs if possible, explore Galle Dutch Fort and relax at the beach.'),
('P03', 4,'Departure from Galle',
'Transfer from Galle to the airport for departure.'),

-- P04: Hill Country 4 Days
('P04', 1,'Airport to Kandy',
'Airport pickup and transfer to Kandy. Optional stop at Pinnawala Elephant Orphanage and overnight stay in Kandy.'),
('P04', 2, 'Kandy to Nuwara Eliya',
'Visit the Temple of the Tooth, enjoy Kandy Lake and transfer to Nuwara Eliya. Visit Ramboda Waterfall and Sri Bhaktha Hanuman Kovil.'),
('P04', 3,'Nuwara Eliya to Colombo',
'Visit a tea plantation and tea factory, explore Little England and Seetha Amman Temple, then transfer to Colombo via St. Clair and Devon Waterfalls.'),
('P04', 4, 'Colombo City and Departure',
'Explore Colombo city, enjoy shopping and transfer to the airport in the evening.'),

-- P05: Classic Sri Lanka 9 Days
('P05', 1, 'Arrival in Negombo',
'Meet the tour representative at the airport, transfer to Negombo, check in and relax after the flight.'),
('P05', 2, 'Negombo to Dambulla',
'Travel to Dambulla via Pinnawala. Visit elephant attractions and check in to the hotel.'),
('P05', 3, 'Sigiriya and Minneriya Safari',
'Visit Sigiriya Rock Fortress, explore cultural sites and enjoy a wildlife safari at Minneriya National Park.'),
('P05', 4, 'Dambulla to Kandy',
'Visit Dambulla Cave Temple and a spice garden. Continue to Kandy, visit the Temple of the Tooth and watch a Kandyan dance show.'),
('P05', 5, 'Kandy to Nuwara Eliya',
'Travel to Nuwara Eliya, visit tea plantations and tea factories, see waterfalls and explore Little England.'),
('P05', 6, 'Nuwara Eliya to Yala',
'Transfer from the hill country to Yala. Stop at Ravana Waterfall and join an evening safari in Yala National Park.'),
('P05', 7, 'Yala to Galle',
'Transfer to Galle after breakfast. Explore Galle Fort and enjoy the sunset from the ramparts.'),
('P05', 8, 'Galle Beach Leisure Day',
'Spend a free day at Galle or Unawatuna beach, explore the fort area and enjoy the coastal atmosphere.'),
('P05', 9, 'Galle to Airport',
'Transfer to the airport for departure after completing the Sri Lanka tour.'),

-- P06: Land and Sea (14 days)
('P06', 1, 'Arrive in Negombo',
 'Airport pickup, transfer to Negombo, hotel check-in and rest.'),
('P06', 2, 'Negombo to Kandy',
 'Explore Negombo fishing village and Lellama; travel to Kandy via Peradeniya Royal Botanical Garden.'),
('P06', 3, 'Explore Kandy',
 'Visit Kandy city, lake and markets; watch a cultural dance show and visit the Temple of the Tooth.'),
('P06', 4, 'Hill Country to Ella',
 'Travel via Ramboda and Nuwara Eliya; take the scenic train from Nanu Oya to Ella.'),
('P06', 5, 'Explore Ella',
 'Hike Little Adams Peak, visit Nine Arch Bridge and a tea estate, then enjoy a local cooking demonstration.'),
('P06', 6, 'Ella to Udawalawe',
 'See Ravana Waterfall en route; visit Elephant Transit Home and take an afternoon safari.'),
('P06', 7, 'Udawalawe to Unawatuna',
 'Transfer to a beach resort in Unawatuna; visit Rumassala and the Japanese Peace Pagoda.'),
('P06', 8, 'Board the Coastal Cruise',
 'Relax in the morning, travel to Mirissa Harbour and cruise into Weligama Bay for dinner on board.'),
('P06', 9, 'Cruise to Kudawella',
 'Sail towards Kudawella; watch for marine life, visit coastal villages and enjoy time in the water.'),
('P06', 10, 'Kalametiya Lagoon',
 'Sail to Kalametiya; explore the lagoon and optionally visit the village or sanctuary.'),
('P06', 11, 'Hiriketiya and Tallala',
 'Visit Hiriketiya for a swim or surf, then continue by boat towards Tallala.'),
('P06', 12, 'Return Towards Rumassala',
 'Sail towards Rumassala; relax at Jungle Beach or visit the Japanese Peace Pagoda.'),
('P06', 13, 'Galle and Weligama Bay',
 'Explore Galle and its fort, then sail back to Weligama Bay for a beach BBQ.'),
('P06', 14, 'Disembark and Depart',
 'Return to Mirissa Harbour, disembark and transfer to the airport.'),

-- P07: Island Romance (9 days)
('P07', 1, 'Arrive in Kotugoda',
 'Airport pickup and transfer to Kotugoda for hotel check-in and rest.'),
('P07', 2, 'Kotugoda to Kandy',
 'Travel to Kandy with an Elephant Freedom Project visit on the way; spend the evening at leisure.'),
('P07', 3, 'Kandy to Ella by Train',
 'Visit the Temple of the Tooth and take a scenic train ride to Ella.'),
('P07', 4, 'Explore Ella',
 'Hike Little Adams Peak, walk near Nine Arch Bridge and relax at the resort.'),
('P07', 5, 'Ella to Yala',
 'See Ravana Waterfall on the way and enjoy an afternoon game drive in Yala National Park.'),
('P07', 6, 'Yala Wildlife Day',
 'Take another wildlife drive in Yala, followed by free time at the resort.'),
('P07', 7, 'Yala to Galle',
 'Travel towards Galle, join a cooking experience near Thalpe and walk along Galle Fort at sunset.'),
('P07', 8, 'Galle Leisure Day',
 'Enjoy a free day at the hotel or explore shops, cafes and the fort area.'),
('P07', 9, 'Departure',
 'Transfer from Galle to the airport.'),

-- P08: Wellness Journey (14 days)
('P08', 1, 'Arrive in Negombo',
 'Airport pickup, transfer to Negombo and rest at the hotel.'),
('P08', 2, 'Negombo to Dambulla',
 'Travel to Dambulla via Ridee Viharaya; visit Dambulla Cave Temple.'),
('P08', 3, 'Nature and Meditation',
 'Visit the Rose Quartz Mountain area, spend time meditating and enjoy a herbal foot massage.'),
('P08', 4, 'Sigiriya to Kandy',
 'Explore Sigiriya Rock Fortress; travel to Kandy and visit the Temple of the Tooth.'),
('P08', 5, 'Meditation in Kandy',
 'Follow a guided meditation programme at Nilambe Meditation Centre.'),
('P08', 6, 'More Meditation Practice',
 'Continue guided meditation, mindfulness and other centre activities.'),
('P08', 7, 'Kandy to Aluthgama',
 'Transfer to Aluthgama, check in at an Ayurveda resort and relax.'),
('P08', 8, 'Ayurveda Programme Day 1',
 'Begin the resort wellness stay with consultation, yoga, meditation and treatments.'),
('P08', 9, 'Ayurveda Programme Day 2',
 'Continue the planned Ayurveda treatments, meditation and yoga activities.'),
('P08', 10, 'Ayurveda Programme Day 3',
 'Continue the resort wellness programme and enjoy free time between sessions.'),
('P08', 11, 'Ayurveda Programme Day 4',
 'Take part in the daily treatments and mindfulness activities.'),
('P08', 12, 'Ayurveda Programme Day 5',
 'Continue the Ayurveda resort programme, including scheduled relaxation activities.'),
('P08', 13, 'Ayurveda Programme Day 6',
 'Complete the six-day resort wellness programme in Aluthgama.'),
('P08', 14, 'Wellness Advice and Departure',
 'Receive end-of-stay advice from the resort doctor and transfer to the airport.'),

-- P09: Rustic Retreats (14 days)
('P09', 1, 'Arrive in Kalutara',
 'Airport pickup, transfer to Kalutara and rest at the hotel.'),
('P09', 2, 'Kalutara Resort Day',
 'Enjoy resort facilities and optional yoga, meditation or nature activities.'),
('P09', 3, 'Sinharaja Forest Excursion',
 'Take a guided forest walk in Sinharaja and return to Kalutara.'),
('P09', 4, 'Kalutara to Belihuloya',
 'Transfer to Belihuloya, join a short nature trek and check in at the campsite.'),
('P09', 5, 'Belihuloya Adventure',
 'Enjoy cycling, zip-lining, canoeing and a campfire dinner.'),
('P09', 6, 'Belihuloya to Gal Oya',
 'Take a morning nature trail, travel to Gal Oya and join a jungle drive.'),
('P09', 7, 'Explore Gal Oya',
 'Take a boat ride and explore nearby communities by bicycle.'),
('P09', 8, 'Gal Oya to Maduru Oya',
 'Travel via Henanigala, meet the Vedda community and take an evening jeep safari.'),
('P09', 9, 'Maduru Oya Safaris',
 'Enjoy morning and evening wildlife drives in Maduru Oya National Park.'),
('P09', 10, 'Maduru Oya to Dambulla',
 'Travel to Dambulla, visit Dambulla Cave Temple and settle into the eco retreat.'),
('P09', 11, 'Pidurangala and Sigiriya Area',
 'Climb Pidurangala for sunrise and explore the Sigiriya countryside.'),
('P09', 12, 'Dambulla Leisure Day',
 'Relax at the retreat; optional activities include bird watching and nature walks.'),
('P09', 13, 'Sigiriya to Makandura',
 'Explore Sigiriya Rock Fortress and transfer to Makandura for an overnight stay.'),
('P09', 14, 'Airport Transfer',
 'Transfer from Makandura to the airport.'),

-- P10: Anasa Wellness (10 days)
('P10', 1, 'Arrive in Galle',
 'Airport pickup, transfer to Galle, hotel check-in and rest.'),
('P10', 2, 'Galle to Bandarawela',
 'Transfer to the wellness resort and begin consultations, fitness and spa sessions.'),
('P10', 3, 'Wellness Programme Day 2',
 'Join yoga and cardio sessions and take part in scheduled detox treatments.'),
('P10', 4, 'Wellness Programme Day 3',
 'Enjoy singing-bowl therapy, hydrotherapy, massage and a healthy cooking class.'),
('P10', 5, 'Wellness Programme Day 4',
 'Continue yoga, fitness and scheduled wellness treatments.'),
('P10', 6, 'Wellness Programme Day 5',
 'Enjoy a sauna session, massage and scheduled fitness activities.'),
('P10', 7, 'Wellness Programme Day 6',
 'Take part in yoga, strength training and the planned resort therapies.'),
('P10', 8, 'Bandarawela to Galle',
 'Finish the wellness programme, receive take-home guidance and travel to Galle via Ella.'),
('P10', 9, 'Explore Galle',
 'Relax at the hotel or beach and walk around Galle Fort in the evening.'),
('P10', 10, 'Departure',
 'Transfer from Galle to the airport.'),

-- P11: Leopard Trails (15 days)
('P11', 1, 'Arrive in Wilpattu',
 'Airport pickup and transfer to Wilpattu for hotel check-in.'),
('P11', 2, 'Wilpattu Full-Day Safari',
 'Spend the day on safari in Wilpattu and enjoy a picnic lunch.'),
('P11', 3, 'Wilpattu Morning Safari',
 'Take another jeep safari, relax at camp and enjoy an evening bush walk.'),
('P11', 4, 'Wilpattu to Habarana',
 'Transfer to Habarana, experience a village visit and take an evening safari.'),
('P11', 5, 'Sigiriya to Kandy',
 'Explore Sigiriya Rock Fortress, transfer to Kandy and watch a cultural dance show.'),
('P11', 6, 'Kandy to Nuwara Eliya',
 'Visit the Temple of the Tooth; travel via Ramboda and visit a tea plantation.'),
('P11', 7, 'Horton Plains',
 'Trek to Horton Plains and Worlds End, then relax in Nuwara Eliya.'),
('P11', 8, 'Nuwara Eliya to Panama',
 'Travel to Panama and check in at the lodge.'),
('P11', 9, 'Kumana Safari Day 1',
 'Travel from Panama to Kumana for a full-day jeep safari and picnic lunch.'),
('P11', 10, 'Kumana Safari Day 2',
 'Return to Kumana for a second full-day safari.'),
('P11', 11, 'Panama to Yala via Bundala',
 'Transfer towards Yala and take an afternoon safari in Bundala.'),
('P11', 12, 'Yala Safari Day 1',
 'Take a full-day safari in Yala and return to the campsite.'),
('P11', 13, 'Yala Safari Day 2',
 'Enjoy another full-day jeep safari and a campfire dinner.'),
('P11', 14, 'Yala to Galle',
 'Transfer to Galle and explore the fort and its ramparts.'),
('P11', 15, 'Departure',
 'Transfer from Galle to the airport.'),

-- P12: Family Escape (15 days)
('P12', 1, 'Arrive in Kotugoda',
 'Airport pickup and transfer to a hotel in Kotugoda.'),
('P12', 2, 'Rest Day in Kotugoda',
 'Relax with the family; an optional wetland boat excursion is mentioned in the source itinerary.'),
('P12', 3, 'Kotugoda to Sigiriya',
 'Travel towards Sigiriya with an elephant-related stop on the way.'),
('P12', 4, 'Sigiriya at Your Pace',
 'Enjoy a flexible day with an optional Sigiriya Rock Fortress visit.'),
('P12', 5, 'Sigiriya to Kandy',
 'Free morning in Sigiriya, followed by a transfer to Kandy.'),
('P12', 6, 'Flexible Kandy Day',
 'Relax at the hotel or visit the Temple of the Tooth and Peradeniya Botanical Garden.'),
('P12', 7, 'Kandy to Ella',
 'Drive to Ella via Ramboda Waterfall and relax at the hotel.'),
('P12', 8, 'Ella Leisure Day',
 'Enjoy a flexible day with optional visits to Little Adams Peak or Nine Arch Bridge.'),
('P12', 9, 'Ella to Yala',
 'Transfer to Yala via Ravana Waterfall and Buduruwagala Temple.'),
('P12', 10, 'Yala Safari',
 'Spend the morning at leisure and take an afternoon jeep safari in Yala.'),
('P12', 11, 'Yala to Tangalle',
 'Transfer to a beach resort in Tangalle and relax.'),
('P12', 12, 'Tangalle Beach Day 1',
 'Enjoy free time at the beach and resort.'),
('P12', 13, 'Tangalle Beach Day 2',
 'Continue the flexible beach stay in Tangalle.'),
('P12', 14, 'Tangalle Beach Day 3',
 'Spend another relaxing day with optional local excursions.'),
('P12', 15, 'Departure',
 'Transfer from Tangalle to the airport.'),

-- P13: Amaya Retreats (12 days)
('P13', 1, 'Arrive in Koggala',
 'Airport pickup and transfer to Koggala for a resort stay.'),
('P13', 2, 'Explore Koggala',
 'Relax at the resort or take an optional lake, cycling or coastal excursion.'),
('P13', 3, 'Koggala to Nanu Oya',
 'Travel to hill country with sightseeing stops and check in at Nanu Oya.'),
('P13', 4, 'Nanu Oya Leisure Day',
 'Enjoy a flexible day of trekking, sightseeing or resort activities.'),
('P13', 5, 'Nanu Oya to Kandy',
 'Take a scenic local train journey to Kandy and check in at the hotel.'),
('P13', 6, 'Relax in Kandy',
 'Enjoy resort time or choose a nature trail and Kandy city visit.'),
('P13', 7, 'Kandy to Pasikudah',
 'Travel to the east coast via Nalanda Gedige and check in at Pasikudah.'),
('P13', 8, 'Pasikudah Beach Day',
 'Relax at the beach or enjoy optional water activities.'),
('P13', 9, 'Pasikudah to Dambulla',
 'Visit Polonnaruwa en route and continue to Dambulla.'),
('P13', 10, 'Sigiriya Exploration',
 'Explore Sigiriya Rock Fortress and enjoy a village experience.'),
('P13', 11, 'Dambulla to Colombo',
 'Visit Dambulla Cave Temple and continue to Colombo for a city walk.'),
('P13', 12, 'Departure',
 'Transfer from Colombo to the airport.'),

-- P14: Off Road Adventure (15 days)
('P14', 1, 'Arrive in Kalpitiya',
 'Airport pickup and transfer to Kalpitiya.'),
('P14', 2, 'Kalpitiya Sand Dunes',
 'Begin the off-road trip with a sand-dune drive and local sightseeing.'),
('P14', 3, 'Kalpitiya to Habarana',
 'Visit Anuradhapura on the way and continue to Habarana.'),
('P14', 4, 'Habarana Four-Wheel Drive',
 'Enjoy an off-road drive across varied terrain near Habarana.'),
('P14', 5, 'Sigiriya to Gal Oya',
 'Explore Sigiriya Rock Fortress and transfer to Gal Oya.'),
('P14', 6, 'Explore Gal Oya',
 'Visit the Vedda community and take a four-wheel-drive park excursion.'),
('P14', 7, 'Gal Oya to Ella',
 'Transfer to Ella, visit Nine Arch Bridge and enjoy a local dinner.'),
('P14', 8, 'Ella Adventure Day',
 'Hike Little Adams Peak and try zip-lining or other adventure activities.'),
('P14', 9, 'Ella to Belihuloya',
 'Take a scenic train ride towards Haputale, visit a tea estate and travel to Belihuloya.'),
('P14', 10, 'Devils Staircase Drive',
 'Enjoy a four-wheel-drive adventure on Devils Staircase and a BBQ dinner.'),
('P14', 11, 'Waterfalls and Hill Routes',
 'Visit Bambarakanda Waterfall and continue the hill-country driving experience.'),
('P14', 12, 'Belihuloya to Udawalawe',
 'Travel to Udawalawe via Kuragala, with sightseeing stops along the way.'),
('P14', 13, 'Udawalawe Safaris',
 'Take morning and afternoon jeep safaris in Udawalawe National Park.'),
('P14', 14, 'Udawalawe to Colombo',
 'Visit Elephant Transit Home and transfer to Colombo.'),
('P14', 15, 'Departure',
 'Transfer from Colombo to the airport.'),

-- P15: Kandy Bentota (6 days)
('P15', 1, 'Arrive in Colombo',
 'Airport pickup and transfer to Colombo; enjoy an evening street-food tour.'),
('P15', 2, 'Colombo to Kandy',
 'Explore Colombo, visit Pinnawala on the way and continue to the Temple of the Tooth in Kandy.'),
('P15', 3, 'Kandy to Nuwara Eliya',
 'Visit Peradeniya Botanical Garden and take a scenic train ride towards Nanu Oya.'),
('P15', 4, 'Nuwara Eliya to Bentota',
 'Visit a tea plantation and Seetha Amman Temple, then travel to Bentota via waterfall viewpoints.'),
('P15', 5, 'Bentota Beach and River',
 'Relax by the beach, take a Madu River boat ride and visit a turtle conservation centre.'),
('P15', 6, 'Departure',
 'Transfer from Bentota to the airport.'),
 
-- P16: Sri Lankan Homes (16 days)
('P16', 1, 'Airport to Negombo',
'Arrive at the airport, transfer to Negombo, check in and rest.'),
('P16', 2, 'Negombo to Sigiriya',
'Travel to Sigiriya and visit Dambulla Cave Temple on the way.'),
('P16', 3, 'Sigiriya and Minneriya',
'Explore Sigiriya Rock Fortress and take an afternoon safari in Minneriya National Park.'),
('P16', 4, 'Sigiriya to Kandy',
'Travel via Nalanda Gedige and Peradeniya Botanical Garden; enjoy Kandy city and a cultural dance show.'),
('P16', 5, 'Kandy Leisure Day',
'Spend a free day at the hotel; optional visits include the Knuckles area or local temples.'),
('P16', 6, 'Kandy to Nuwara Eliya',
'Travel via Ramboda Waterfall and Sri Bhaktha Hanuman Temple; visit a tea plantation and factory.'),
('P16', 7, 'Nuwara Eliya Leisure',
'Relax in Nuwara Eliya; optional activities include a tea experience or Horton Plains trek.'),
('P16', 8, 'Nuwara Eliya to Wellawaya',
'Visit a strawberry farm, take a scenic train ride towards Demodara and see Nine Arch Bridge.'),
('P16', 9, 'Wellawaya Experiences',
'Free day for optional village walks, outdoor activities, waterfalls or cooking experiences.'),
('P16', 10, 'Wellawaya to Pottuvil',
'Travel through countryside to Pottuvil and relax at the beach.'),
('P16', 11, 'Pottuvil Beach Day',
'Enjoy a free beach day or choose a local excursion.'),
('P16', 12, 'Pottuvil to Yala',
'Transfer to Yala and take an afternoon jeep safari.'),
('P16', 13, 'Yala to Galle',
'Travel to Galle and explore Galle Dutch Fort and the old town.'),
('P16', 14, 'Galle and Unawatuna',
'Enjoy the beaches of Galle or Unawatuna; optional local activities are available.'),
('P16', 15, 'Galle to Colombo',
'Travel towards Colombo via a Madu River boat safari and the Kosgoda turtle conservation project.'),
('P16', 16, 'Colombo to Airport',
'Transfer from Colombo to the airport for departure.'),

-- P17: Cinnamon Local Vibe (14 days)
('P17', 1, 'Arrive in Colombo',
'Airport pickup, transfer to Colombo and check in at the hotel.'),
('P17', 2, 'Colombo to Habarana',
'Visit Dambulla Cave Temple on the way to Habarana and settle in at the hotel.'),
('P17', 3, 'Anuradhapura Excursion',
'Explore Anuradhapura and experience a village excursion before returning to Habarana.'),
('P17', 4, 'Sigiriya to Trincomalee',
'Explore Sigiriya Rock Fortress and continue to Trincomalee for a beach stay.'),
('P17', 5, 'Trincomalee Beach',
'Spend a leisure day at the beach; marine excursions are optional.'),
('P17', 6, 'Trincomalee to Kandy',
'Travel to Kandy via Nalanda Gedige and visit Peradeniya Botanical Garden.'),
('P17', 7, 'Kandy Leisure Day',
'Visit the Temple of the Tooth and spend the rest of the day at leisure.'),
('P17', 8, 'Kandy to Nuwara Eliya',
'See Ramboda Waterfall, visit a tea plantation and explore Nuwara Eliya.'),
('P17', 9, 'Train and Transfer to Yala',
'Take a scenic train towards Ella, visit Nine Arch Bridge and continue to Yala.'),
('P17', 10, 'Yala Safari',
'Enjoy a full-day safari in Yala National Park.'),
('P17', 11, 'Yala to Bentota',
'Travel via Galle, visit a turtle conservation project and take a Madu River boat safari.'),
('P17', 12, 'Bentota Resort Day',
'Relax at Bentota or choose optional water and cultural activities.'),
('P17', 13, 'Bentota Beach Day',
'Spend another day at leisure on Bentota beach.'),
('P17', 14, 'Bentota to Airport',
'Transfer from Bentota to the airport for departure.'),

-- P18: Feathered Trails (15 days)
('P18', 1, 'Arrive in Wilpattu',
'Airport pickup and transfer to Wilpattu.'),
('P18', 2, 'Wilpattu Birding Safari',
'Take a full-day jeep safari with time to observe wildlife and birdlife.'),
('P18', 3, 'Wilpattu to Mannar',
'Travel to Mannar and explore its countryside, lagoon and fort area.'),
('P18', 4, 'Mannar Wetlands',
'Visit Mannar wetland and coastal birding locations.'),
('P18', 5, 'Mannar to Sigiriya',
'Travel to Sigiriya and visit the rock fortress near sunset.'),
('P18', 6, 'Sigiriya Sanctuary',
'Explore the Sigiriya sanctuary and enjoy a local village experience.'),
('P18', 7, 'Sigiriya to Kitulgala',
'Visit Dambulla Cave Temple on the way and enjoy a rafting activity in Kitulgala.'),
('P18', 8, 'Kitulgala to Nuwara Eliya',
'Take a forest walk in Kitulgala, then travel to Nuwara Eliya via waterfall viewpoints.'),
('P18', 9, 'Horton Plains Birding',
'Trek through Horton Plains and visit Worlds End before returning to Nuwara Eliya.'),
('P18', 10, 'Yala Safari and Bundala',
'Travel via Ravana Waterfall, take a Yala safari and stay near Bundala.'),
('P18', 11, 'Bundala Birding Safari',
'Explore Bundala National Park and its wetland birdlife.'),
('P18', 12, 'Bundala to Udawalawe',
'Visit Elephant Transit Home and take an afternoon safari in Udawalawe.'),
('P18', 13, 'Udawalawe to Sinharaja',
'Travel to Sinharaja and enjoy an evening nature walk.'),
('P18', 14, 'Sinharaja Forest Trek',
'Explore the rainforest with a focus on birds and other wildlife.'),
('P18', 15, 'Departure',
'Transfer from Sinharaja to the airport.'),

-- P19: Echoes of Wild (15 days)
('P19', 1, 'Arrive in Wilpattu',
'Airport pickup and transfer to Wilpattu.'),
('P19', 2, 'Wilpattu Safari',
'Take a full-day jeep safari in Wilpattu with a picnic lunch.'),
('P19', 3, 'Wilpattu to Sigiriya',
'Travel to Sigiriya, visit the rock fortress and relax in the evening.'),
('P19', 4, 'Dambulla and Village Life',
'Visit Dambulla Cave Temple, enjoy a village experience and take an evening loris-watching tour.'),
('P19', 5, 'Polonnaruwa to Wasgamuwa',
'Explore Polonnaruwa by bicycle, then transfer to Wasgamuwa.'),
('P19', 6, 'Wasgamuwa Safari',
'Take a morning jeep safari in Wasgamuwa National Park.'),
('P19', 7, 'Wasgamuwa to Nuwara Eliya',
'Travel to Nuwara Eliya and visit a tea plantation, tea factory and Gregory Lake area.'),
('P19', 8, 'Horton Plains Trek',
'Trek through Horton Plains to Worlds End and return to Nuwara Eliya.'),
('P19', 9, 'Nuwara Eliya to Gal Oya',
'Transfer to Gal Oya, take a safari and enjoy an evening nature walk.'),
('P19', 10, 'Gal Oya Boat Excursion',
'Take a morning boat ride and explore the surrounding area by bicycle.'),
('P19', 11, 'Gal Oya to Kumana',
'Take a birding excursion at Kiri Oruwa Lake and transfer to Kumana.'),
('P19', 12, 'Kumana Safari',
'Enjoy a full-day jeep safari in Kumana National Park.'),
('P19', 13, 'Kumana to Mirissa',
'Travel to Mirissa and spend the evening near the coast.'),
('P19', 14, 'Mirissa Boat Trip',
'Take a morning boat trip to look for whales and dolphins, then relax in Mirissa.'),
('P19', 15, 'Departure',
'Transfer from Mirissa to the airport.'),

-- P20: Sri Lanka and Maldives (15 days)
('P20', 1, 'Arrive in Colombo',
'Airport pickup, transfer to Colombo and rest at the hotel.'),
('P20', 2, 'Explore Colombo',
'Visit Colombo attractions and Dehiwala Zoo; the document also includes karting in Bandaragama.'),
('P20', 3, 'Colombo to Kitulgala',
'Transfer to Kitulgala, enjoy a rafting activity and have dinner by the Kelani River.'),
('P20', 4, 'Kitulgala Activities',
'Enjoy bird watching, canoeing or kayaking and explore the Kitulgala area.'),
('P20', 5, 'Kitulgala to Nuwara Eliya',
'Travel via St. Clair and Devon Waterfalls; visit a tea plantation and factory.'),
('P20', 6, 'Horton Plains',
'Trek in Horton Plains, visit Worlds End and return to Nuwara Eliya.'),
('P20', 7, 'Train to Ella',
'Take a scenic train journey from Nanu Oya to Ella and visit Nine Arch Bridge.'),
('P20', 8, 'Ella Adventure Day',
'Hike Little Adams Peak and enjoy adventure and cooking activities.'),
('P20', 9, 'Ella to Yala',
'Travel via Ravana Waterfall and take an afternoon Yala jeep safari.'),
('P20', 10, 'Yala Wildlife Day',
'Take a morning game drive and enjoy leisure time afterwards.'),
('P20', 11, 'Fly to Maldives',
'Transfer to the Sri Lankan airport, fly to Male and transfer to the Maldives resort.'),
('P20', 12, 'Maldives Beach Day 1',
'Relax at the resort; optional activities include water sports and beach games.'),
('P20', 13, 'Maldives Beach Day 2',
'Enjoy resort time and optional snorkeling, kayaking or an island excursion.'),
('P20', 14, 'Maldives Beach Day 3',
'Spend another leisure day at the resort with optional marine activities.'),
('P20', 15, 'Maldives Departure',
'Transfer to Male airport for the flight home.');
 
 ;

DROP TABLE IF EXISTS TourPackage;
